name: quirckly
description: "A Task Management App for you and your team."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  go_router: ^14.4.1
  shared_preferences: ^2.3.2
  get_it: ^8.0.2
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  http: ^1.2.2
  dartz: ^0.10.1
  google_fonts: ^6.2.1
  simple_gradient_text: ^1.3.0
  flutter_svg: ^2.0.14

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  build_runner: ^2.4.13

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  # icons
    - assets/icons/menu_icon.svg
    - assets/icons/next_icon.svg

  # images 
    - assets/images/onboarding_bg.png
    - assets/images/onboarding_illustration.png
    - assets/images/auth_illustration.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
